## Clock signal
set_property PACKAGE_PIN W5 [get_ports clock]
	set_property IOSTANDARD LVCMOS33 [get_ports clock]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clock]

## resultado
set_property PACKAGE_PIN U16 [get_ports {resultado[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[0]}]
set_property PACKAGE_PIN E19 [get_ports {resultado[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[1]}]
set_property PACKAGE_PIN U19 [get_ports {resultado[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[2]}]
set_property PACKAGE_PIN V19 [get_ports {resultado[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[3]}]
set_property PACKAGE_PIN W18 [get_ports {resultado[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[4]}]
set_property PACKAGE_PIN U15 [get_ports {resultado[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[5]}]
set_property PACKAGE_PIN U14 [get_ports {resultado[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[6]}]
set_property PACKAGE_PIN V14 [get_ports {resultado[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[7]}]
set_property PACKAGE_PIN V13 [get_ports {resultado[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[8]}]
set_property PACKAGE_PIN V3 [get_ports {resultado[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[9]}]
set_property PACKAGE_PIN W3 [get_ports {resultado[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[10]}]
set_property PACKAGE_PIN U3 [get_ports {resultado[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[11]}]
set_property PACKAGE_PIN P3 [get_ports {resultado[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[12]}]
set_property PACKAGE_PIN N3 [get_ports {resultado[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[13]}]
set_property PACKAGE_PIN P1 [get_ports {resultado[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[14]}]
set_property PACKAGE_PIN L1 [get_ports {resultado[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {resultado[15]}]

## dato
set_property PACKAGE_PIN V17 [get_ports {dato[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[0]}]
set_property PACKAGE_PIN V16 [get_ports {dato[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[1]}]
set_property PACKAGE_PIN W16 [get_ports {dato[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[2]}]
set_property PACKAGE_PIN W17 [get_ports {dato[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[3]}]
set_property PACKAGE_PIN W15 [get_ports {dato[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[4]}]
set_property PACKAGE_PIN V15 [get_ports {dato[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[5]}]
set_property PACKAGE_PIN W14 [get_ports {dato[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[6]}]
set_property PACKAGE_PIN W13 [get_ports {dato[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[7]}]
set_property PACKAGE_PIN V2 [get_ports {dato[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[8]}]
set_property PACKAGE_PIN T3 [get_ports {dato[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[9]}]
set_property PACKAGE_PIN T2 [get_ports {dato[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[10]}]
set_property PACKAGE_PIN R3 [get_ports {dato[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[11]}]
set_property PACKAGE_PIN W2 [get_ports {dato[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[12]}]
set_property PACKAGE_PIN U1 [get_ports {dato[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[13]}]
set_property PACKAGE_PIN T1 [get_ports {dato[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[14]}]
set_property PACKAGE_PIN R2 [get_ports {dato[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {dato[15]}]
	

